### ISSUE TITLE
Missing License from parent library

### ISSUE THREAD

**Issue by BTMorton** [arup-banerjee/ngx-draggable-widget#3]
Hi,

You seem to have copied my library https://github.com/BTMorton/angular2-grid with the addition of your [pull request changes](https://github.com/BTMorton/angular2-grid/pull/253) and published it as a separate, standalone library. It's published under the MIT license, so that's something you're allowed to do, under the condition that you maintain the parent license and copyright.

Please add my license and copyright (available at https://github.com/BTMorton/angular2-grid/blob/master/LICENSE) to your repository's LICENSE.

An acknowledgement somewhere in the README would also be appreciated, but is not required.

Cheers,
Ben

**Comment by arup-banerjee** [comment]
Good Morning Ben,
It will be fair to suggest that I have used initial code base from https://github.com/BTMorton/angular2-to effect a framework which is widget centric and moving towards that direction, rather than pixel based grid system which is what angular2-grid is and angular-gridster is.

Currently framework of angular2-grid and angular-gridster are similar. Therefore to suggest I include your LICENSE and not angular-gridster may not be fair and also may be incorrect because essentially  
the overall framework of ngx-draggable-widget is going on a different direction which is widget based rather than grid pixel based.
 
Secondly I would have been happy to go alongside your work being a contributor , but my code and features are way different . Just a single pull request is still pending over a week. t

The code base currently in  ngx-draggable-widget has significant changes .Think about it .... would you have agreed. They are fundamentally different ?

Having said, I do like your great work and I'm inspired and got my own ideas from you and also other open-sources. I'll be very happy to include you in my acknowledgement list. 

I hope you agree with the suggestion.

**Comment by BTMorton** [comment]
The core difference between my library and angular-gridster here is that you have used my entire code base as a kick start, including core things like the item grid and the cascading algorithm. If we compare the code it is almost identical in 90% of the main source files, and you yourself admit that you have used my initial code base. That is why I think you should include my LICENSE and it has nothing to do with the ideology of your repository.

In fact, comparing the main demo gives a good idea of the amount of code overlap that still exists:
![image](https://user-images.githubusercontent.com/9026309/29819026-c27b4fbe-8cb6-11e7-8f03-16fbf0a0d534.png)

I appreciate that you may have been frustrated by how slow-moving my repository can be, and that is fine. You are allowed to take the code and spin it off into a new library, that's permitted to you with my license, as long as you include said license and copyright in your new library.

It is worth mentioning that the single pull request you refer to appears to be yours from a difference account, and those changes also appear to be one of the main differences between our two libraries currently. Also, the speed of my maintenance does not at all change the fact you have used my code.

I would not agree that they are fundamentally different. The fundamentals such as grid state, dragging, resizing and cascading are almost identical.

Thank you for offering to give me an acknowledgement; as I said, it would be appreciated. My core issue here isn't the ideology behind your library, I wish you luck with your slightly modified direction, however, you have taken my code currently without any acknowledgement at all and all I am asking is that you include the correct copyright for said code until such a time as you have removed or rewritten all of it.

Let me also make clear that I only wish for the copyright for the sections of code which are mine, and you are free to make that explicit. Additionally, I am not interested in anything you may gain from this library. That obviously will remain yours. I think it is a fair request as you yourself admit having used my code.

**Comment by arup-banerjee** [comment]
Dear Ben,

 

I’ll not take the credit which is yours . I’ll make sure the credit which is due to you will remain with you and even more. 

For that matter anybody even if he or she contributes one line of code that will hold true.

It is just that I’m too much packed up and did not have the time. Give me sometime and I’ll sort out by end of next week.

 

I want to contribute and everyone else to contribute at the end of the day. These things will be sorted out .. don’t worry about those  at-least with me.

 

You need not spend your time in explaining these , I understand . You have a brighter mind which is better devoted to the better and more interesting causes!!

 

😊

Arup

**Comment by BTMorton** [comment]
Thank you, kindly.

I share the same principle of openness and encouraging contributions and I wish you all the best with your library.

Cheers,
Ben
